<?xml version="1.0" encoding="UTF-8"?>
<project name="kotlin-in-java"
         default="run"
         basedir="."
         xmlns:ivy="antlib:org.apache.ivy.ant">

    <property name="compile.release" value="21"/>
    
    <property name="src.java" value="src/main/java"/>
    <property name="src.kotlin" value="annotations_/src/main/kotlin"/> 

    <property name="build.dir" value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="lib.dir" value="${build.dir}/lib"/>

    <property name="main.class" value="org.example.MainKt"/>

    <path id="ivy.classpath">
        <fileset dir="lib">
            <include name="ivy-*.jar"/>
        </fileset>
    </path>

    <taskdef uri="antlib:org.apache.ivy.ant"
             resource="org/apache/ivy/ant/antlib.xml"
             classpathref="ivy.classpath"/>

    <path id="compile.classpath">
        <fileset dir="${lib.dir}">
            <include name="**/*.jar"/>
        </fileset>
    </path>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="init">
        <mkdir dir="${classes.dir}"/>
        <mkdir dir="${lib.dir}"/>
        <mkdir dir="${src.java}"/>
    </target>

    <target name="resolve" depends="init">
        <ivy:resolve/>
        <ivy:retrieve pattern="${lib.dir}/[artifact]-[revision]-[type]-[classifier].jar"/>
    </target>

    <target name="compile-kotlin" depends="resolve">
        <echo message="Compiling Kotlin source from ${src.kotlin}..."/>
        <java classname="org.jetbrains.kotlin.cli.jvm.K2JVMCompiler" 
            fork="true" 
            failonerror="true">
            
            <classpath>
                <fileset dir="${lib.dir}">
                    <include name="kotlin-compiler-embeddable-*.jar"/>
                    <include name="kotlin-stdlib-*.jar"/>
                    <include name="kotlin-reflect-*.jar"/>
                    <include name="kotlinx-coroutines-core-*.jar"/>
                </fileset>
            </classpath>
            
            <arg value="-no-stdlib"/>
            <arg value="-Xdisable-default-scripting-plugin"/>
            <arg value="-d"/><arg value="${classes.dir}"/>
            
            <arg value="-classpath"/>
            <arg pathref="compile.classpath"/>
            
            <arg value="${src.kotlin}"/>
        </java>
    </target>

    <target name="compile-java" depends="compile-kotlin">
        <javac srcdir="${src.java}"
               destdir="${classes.dir}"
               release="${compile.release}"
               includeantruntime="false"
               failonerror="false">
            <classpath refid="compile.classpath"/>
            <compilerarg value="--enable-preview"/>
        </javac>
    </target>

    <target name="compile" depends="compile-java"/>

    <target name="run" depends="compile">
        <echo message="------------------------------------------------"/>
        <echo message="Running Main Class: ${main.class}"/>
        <echo message="------------------------------------------------"/>
        
        <java classname="${main.class}" 
              fork="true" 
              failonerror="true"
              inputstring="2"> <classpath>
                <pathelement location="${classes.dir}"/>
                <path refid="compile.classpath"/>
            </classpath>

            <jvmarg value="--enable-preview"/>
            <jvmarg value="--add-opens=java.base/java.nio=ALL-UNNAMED"/>
            <jvmarg value="--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"/>
            
            <jvmarg value="-Dorg.slf4j.simpleLogger.defaultLogLevel=error"/>
            <jvmarg value="-Dspark.ui.showConsoleProgress=false"/>
        </java>
    </target>

</project>