name: Java CI

on:
  push:
    branches:
      - javac_  # Adjust the branch name as needed
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=example --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: sample_db
          MYSQL_USER: sample_user
          MYSQL_PASSWORD: sample_password

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Specify your Java version
          distribution: 'adopt'
      
      # --------------------
      # Install Ant
      # --------------------
      - name: Install Apache Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          mkdir -p lib
          curl -L https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.2/ivy-2.5.2.jar -o lib/ivy-2.5.2.jar
          ant -version

      # --------------------
      # Ant build
      # --------------------
      - name: Build with Ant
        run: |
          # if build.xml is at repo root
          ant clean run

      - name: Build and run with Maven
        run: |
         mvn clean install && mvn compile && mvn exec:java <<EOF
         2
         EOF

      - name: Build Kotlin annotations and run with Maven
        run: |
          cd annotations_
          mvn clean install && mvn clean compile && mvn exec:java